spring.flyway.enabled=false
spring.flyway.baselineOnMigrate=false
spring.main.allow-bean-definition-overriding=true
azure.blob.endpointFormat=http://localhost:10000/devstoreaccount1
azure.finalStorage.accountName=testAccount
azure.finalStorage.connectionString=AccountKey=testString
azure.ingestStorage.accountName=devstoreaccount1
azure.ingestStorage.connectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;\
AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;\
BlobEndpoint=http://%s:%d/devstoreaccount1;
azure.vodafoneStorage.accountName=testAccount
azure.vodafoneStorage.connectionString=AccountKey=testString
api.name=${API_NAME}
api.specsPath=specs/${API_NAME}
