parameters:
  - name: environment
    displayName: Environment
    type: object
    default:
      - Staging:
        serviceConnection: 'DTS-SHAREDSERVICES-STG'
        kvName: 'pre-hmctskv-stg'
        sourceDbName: 'pre-pdb-stg'
      - Demo:
        serviceConnection: 'DTS-SHAREDSERVICES-DEMO'
        kvName: 'pre-hmctskv-demo'
        sourceDbName: 'pre-pdb-demo'
      - Production:
        serviceConnection: 'DTS-SHAREDSERVICES-PROD'
        kvName: 'pre-hmctskv-prod'
        sourceDbName: 'pre-pdb-prod'

# Runs ad-hoc
trigger:
- none

pool: hmcts-sds-ptl

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: ${{ parameters.environment.serviceConnection }}
    KeyVaultName: ${{ parameters.environment.kvName }}
    SecretsFilter: 'api-POSTGRES-USER,api-POSTGRES-PASS,api-POSTGRES-HOST'
    RunAsPreJob: true

- script: pip install -r bin/migration/requirements.txt
  displayName: 'Install dependencies'

#export SOURCE_DB_NAME=${{ parameters.environment.sourceDbName }}
#export SOURCE_DB_USER=$(api-POSTGRES-USER)
#export SOURCE_DB_PASSWORD=$(api-POSTGRES-PASS)
#export SOURCE_DB_HOST=$(api-POSTGRES-HOST)
#export DESTINATION_DB_NAME=api
#export DESTINATION_DB_USER=$(api-POSTGRES-USER)
#export DESTINATION_DB_PASSWORD=$(api-POSTGRES-PASS)
#export DESTINATION_DB_HOST=$(api-POSTGRES-HOST)
