name: Insert country wide court data

# Runs ad-hoc
trigger: none
pr: none

pool: hmcts-sds-ptl

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Staging
    values:
      - Staging
      - Demo
      - Production

  - name: run_court_upsert
    displayName: Execute insert script
    type: boolean
    default: false

variables:
  - name: 'environment'
    value: ${{ parameters.environment }}

  - name: 'serviceConnection'
    ${{ if eq(variables['environment'], 'Production') }}:
      value: 'DTS-SHAREDSERVICES-PROD'
    ${{ if eq(variables['environment'], 'Demo') }}:
      value: 'DTS-SHAREDSERVICES-DEMO'
    ${{ if eq(variables['environment'], 'Staging') }}:
      value: 'DTS-SHAREDSERVICES-STG'

  - name: 'envShortName'
    ${{ if eq(variables['environment'], 'Production') }}:
      value: 'prod'
    ${{ if eq(variables['environment'], 'Demo') }}:
      value: 'demo'
    ${{ if eq(variables['environment'], 'Staging') }}:
      value: 'stg'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(serviceConnection)
    KeyVaultName: 'pre-hmctskv-$(envShortName)'
    SecretsFilter: 'api-POSTGRES-USER,api-POSTGRES-PASS,api-POSTGRES-HOST'
    RunAsPreJob: true

- task: Bash@3
  condition: ${{ eq(parameters.run_court_upsert, true) }}
  inputs:
    targetType: 'inline'
    script: |
      export DESTINATION_DB_NAME="api"
      export DESTINATION_DB_USER="$(api-POSTGRES-USER)"
      export DESTINATION_DB_PASSWORD="$(api-POSTGRES-PASS)"
      export DESTINATION_DB_HOST="$(api-POSTGRES-HOST)"
      python3 bin/court_upsert/main.py
  displayName: 'Execute court upsert script'


