name: Import Power Platform into Test

# Runs ad-hoc
trigger: none
pr: none

pool: hmcts-sds-ptl

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Staging
    values:
      - Staging
      - Demo
      - Production

  - name: run_migration_script
    displayName: Execute migration script
    type: boolean
    default: false

  - name: run_recording_duration_script
    displayName: Update recording duration
    type: boolean
    default: false

variables:
  - name: 'environment'
    value: ${{ parameters.environment }}

  - name: 'serviceConnection'
    ${{ if eq(variables['environment'], 'Production') }}:
      value: 'DTS-SHAREDSERVICES-PROD'
    ${{ if eq(variables['environment'], 'Demo') }}:
      value: 'DTS-SHAREDSERVICES-DEMO'
    ${{ if eq(variables['environment'], 'Staging') }}:
      value: 'DTS-SHAREDSERVICES-STG'

  - name: 'envShortName'
    ${{ if eq(variables['environment'], 'Production') }}:
      value: 'prod'
    ${{ if eq(variables['environment'], 'Demo') }}:
      value: 'demo'
    ${{ if eq(variables['environment'], 'Staging') }}:
      value: 'stg'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(serviceConnection)
    KeyVaultName: 'pre-hmctskv-$(envShortName)'
    SecretsFilter: 'api-POSTGRES-USER,api-POSTGRES-PASS,api-POSTGRES-HOST,finalsa-storage-account-connection-string'
    RunAsPreJob: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:{TOOLCACHE_PATH}/Python/{VERSION}/x64/lib/"
      python3 --version
      mkdir -p migration_reports/logs
      touch migration_reports/logs/error.log

- script: pip install -r bin/migration/requirements.txt
  displayName: 'Install dependencies'

- task: Bash@3
  condition: ${{ eq(parameters.run_migration_script, true) }}
  inputs:
    targetType: 'inline'
    script: |
      export SOURCE_DB_NAME="pre-pdb-$(envShortName)"
      export SOURCE_DB_USER="$(api-POSTGRES-USER)"
      export SOURCE_DB_PASSWORD="$(api-POSTGRES-PASS)"
      export SOURCE_DB_HOST="$(api-POSTGRES-HOST)"
      export DESTINATION_DB_NAME="api"
      export DESTINATION_DB_USER="$(api-POSTGRES-USER)"
      export DESTINATION_DB_PASSWORD="$(api-POSTGRES-PASS)"
      export DESTINATION_DB_HOST="$(api-POSTGRES-HOST)"
      python3 bin/migration/main.py
  displayName: 'Execute migration script'


- task: Bash@3
  condition: ${{ eq(parameters.run_recording_duration_script, true) }}
  inputs:
    targetType: 'inline'
    script: |
      export DESTINATION_DB_NAME="api"
      export DESTINATION_DB_USER="$(api-POSTGRES-USER)"
      export DESTINATION_DB_PASSWORD="$(api-POSTGRES-PASS)"
      export DESTINATION_DB_HOST="$(api-POSTGRES-HOST)"
      export AZURE_STORAGE_CONNECTION_STRING="$(finalsa-storage-account-connection-string)"
      python3 bin/migration/azure_storage_utils/main.py
  displayName: 'Update recording duration'
