version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pre
      POSTGRES_USER: pre
      POSTGRES_DB: pre

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
