services:

  db:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: pre
      POSTGRES_USER: pre
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
