version: '3.1'

services:

  db:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: pre
      POSTGRES_USER: pre
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
