apiVersion: v2
appVersion: "1.0"
description: A Helm chart for pre-api App
name: pre-api
home: https://github.com/hmcts/pre-api
version: 0.0.55
maintainers:
  - name: HMCTS pre team
dependencies:
  - name: java
    version: 5.2.1
    repository: oci://hmctspublic.azurecr.io/helm
    condition: java.enabled
  - name: job
    version: 2.1.3
    repository: oci://hmctspublic.azurecr.io/helm
    condition: job.enabled
