apiVersion: v2
appVersion: "1.0"
description: A Helm chart for pre-api App
name: pre-api
home: https://github.com/hmcts/pre-api
version: 0.0.53
maintainers:
  - name: HMCTS pre team
dependencies:
  - name: java
    version: 5.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: java.enabled
  - name: job
    version: 2.1.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: job.enabled
  - name: function
    version: 2.5.3
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: postgresql
    version: 1.0.2
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: postgresql.enabled
