java:
  applicationPort:
  image: 'hmctspublic.azurecr.io/pre/api:latest'
  ingressHost: pre-api.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: pre
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    pre:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
