java:
  environment:
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
  # Don't modify this file beyond this line, it is only needed for the pipeline to set the image and ingressHost
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
