java:
  postgresql:
    enabled: true
  keyVaults:
    pre-hmctskv:
      secrets:
        - name: tenantid
          alias: AZURE_TENANT_ID
        - name: mediaservice
          alias: AZURE_MEDIA_SERVICES_ACCOUNT_NAME
        - name: resourcegroup
          alias: AZURE_RESOURCE_GROUP
        - name: subscriptionid
          alias: AZURE_SUBSCRIPTION_ID
        - name: clientid
          alias: AZURE_CLIENT_ID
        - name: clientsecret
          alias: AZURE_CLIENT_SECRET
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USER: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    APIM_ENABLED: false
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
