# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  environment:
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    APIM_URI: https://sds-api-mgmt.staging.platform.hmcts.net
    MEDIA_KIND_SUBSCRIPTION: pre-mediakind-stg
    PLATFORM_ENV_TAG: Staging
    AZURE_INGEST_SA: preingestsastg
    AZURE_FINAL_SA: prefinalsastg
    AZURE_VF_SA: prevodasastg
    MEDIA_SERVICE: MediaKind
    ENABLE_NEW_EMAIL_SERVICE: true
    ENABLE_STREAMING_LOCATOR_ON_START: true
    ENABLE_AUTOMATED_EDITING: true
    TASK_BATCH_IMPORT_MISSING_ASSETS_BATCH_SIZE: 20
    TASK_BATCH_IMPORT_MISSING_ASSETS_POLL_INTERVAL: 10000
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
