java:
  postgresql:
    enabled: true
  keyVaults:
    pre-hmctskv-stg:
      excludeEnvironmentSuffix: true
      secrets:
        - name: pp-clientid
          alias: AZURE_CLIENT_ID
        - name: pp-clientsecret
          alias: AZURE_CLIENT_SECRET
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database}}"
    POSTGRES_USER: "{{ .Values.postgresql.auth.username}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    APIM_ENABLED: false
    AZURE_MEDIA_SERVICES_ACCOUNT_NAME: preamsstg
    AZURE_RESOURCE_GROUP: pre-stg
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
