# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  keyVaults:
    pre-hmctskv:
      secrets:
        - name: api-MKIO-TOKEN
          alias: MEDIA_KIND_TOKEN
  environment:
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    APIM_URI: https://sds-api-mgmt.staging.platform.hmcts.net
    AZURE_SUBSCRIPTION_ID: 3eec5bde-7feb-4566-bfb6-805df6e10b90
    AZURE_TENANT_ID: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
    AZURE_MEDIA_SERVICES_ACCOUNT_NAME: preamstest
    AZURE_RESOURCE_GROUP: pre-test
    MEDIA_KIND_SUBSCRIPTION: pre-mediakind-stg
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
