-- Migration to change values of enums to be capitalized

ALTER TYPE public.COURT_TYPE RENAME VALUE 'crown' TO 'CROWN';
ALTER TYPE public.COURT_TYPE RENAME VALUE 'magistrate' TO 'MAGISTRATE';
ALTER TYPE public.COURT_TYPE RENAME VALUE 'family' TO 'FAMILY';

ALTER TYPE public.PARTICIPANT_TYPE RENAME VALUE 'witness' TO 'WITNESS';
ALTER TYPE public.PARTICIPANT_TYPE RENAME VALUE 'defendant' TO 'DEFENDANT';

ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'standby' TO 'STANDBY';
ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'initialisation' TO 'INITIALIZATION';
ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'recording' TO 'RECORDING';
ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'finished' TO 'FINISHED';
ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'processing' TO 'PROCESSING';
ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'available' TO 'AVAILABLE';
ALTER TYPE public.RECORDING_STATUS RENAME VALUE 'future' TO 'FUTURE';

ALTER TYPE public.RECORDING_ORIGIN RENAME VALUE 'pre' TO 'PRE';
ALTER TYPE public.RECORDING_ORIGIN RENAME VALUE 'vodafone' TO 'VODAFONE';

ALTER TYPE public.AUDIT_LOG_SOURCE RENAME VALUE 'application' TO 'APPLICATION';
ALTER TYPE public.AUDIT_LOG_SOURCE RENAME VALUE 'portal' TO 'PORTAL';
ALTER TYPE public.AUDIT_LOG_SOURCE RENAME VALUE 'admin' TO 'ADMIN';
ALTER TYPE public.AUDIT_LOG_SOURCE RENAME VALUE 'auto' TO 'AUTO';

ALTER TYPE public.AUDIT_LOG_TYPE RENAME VALUE 'create' TO 'CREATE';
ALTER TYPE public.AUDIT_LOG_TYPE RENAME VALUE 'update' TO 'UPDATE';
ALTER TYPE public.AUDIT_LOG_TYPE RENAME VALUE 'delete' TO 'DELETE';
ALTER TYPE public.AUDIT_LOG_TYPE RENAME VALUE 'action' TO 'ACTION';

ALTER TYPE public.ACCESS_STATUS RENAME VALUE 'invitation_sent' TO 'INVITATION_SENT';
ALTER TYPE public.ACCESS_STATUS RENAME VALUE 'registered' TO 'REGISTERED';
ALTER TYPE public.ACCESS_STATUS RENAME VALUE 'active' TO 'ACTIVE';
ALTER TYPE public.ACCESS_STATUS RENAME VALUE 'inactive' TO 'INACTIVE';

ALTER TABLE public.portal_access ALTER COLUMN status SET DEFAULT 'INVITATION_SENT'::access_status;
