DROP TYPE public.RECORDING_STATUS CASCADE;

CREATE TYPE public.RECORDING_STATUS AS ENUM (
    'STANDBY',
    'INITIALISATION',
    'RECORDING',
    'RECORDING_AVAILABLE',
    'PROCESSING',
    'FAILURE',
    'NO_RECORDING'
);

ALTER TABLE public.capture_sessions ADD COLUMN status RECORDING_STATUS;
