DROP TYPE public.ACCESS_STATUS CASCADE;

CREATE TYPE public.ACCESS_STATUS AS ENUM (
    'ACTIVE',
    'INACTIVE'
);

ALTER TABLE public.portal_access ADD COLUMN status ACCESS_STATUS NOT NULL DEFAULT 'INACTIVE'::ACCESS_STATUS;
ALTER TABLE public.portal_access ADD COLUMN terms_accepted_at TIMESTAMPTZ;