CREATE TYPE public.CASE_STATE AS ENUM (
    'OPEN',
    'PENDING_CLOSURE',
    'CLOSED'
);

ALTER TABLE public.cases
ADD COLUMN state CASE_STATE NOT NULL DEFAULT 'OPEN',
ADD COLUMN closed_at timestamptz;
