ALTER TABLE public.edit_requests ADD COLUMN jointly_agreed BOOLEAN;
ALTER TABLE public.edit_requests ADD COLUMN rejection_reason VARCHAR(512);
ALTER TABLE public.edit_requests ADD COLUMN approved_at TIMESTAMPTZ;
ALTER TABLE public.edit_requests ADD COLUMN approved_by VARCHAR(100);

ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'DRAFT';
ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'SUBMITTED';
ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'APPROVED';
ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'REJECTED';
