ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'DRAFT';
ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'SUBMITTED';
ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'APPROVED';
ALTER TYPE public.EDIT_REQUEST_STATUS ADD VALUE 'REJECTED';
