name: Log in to Azure Container Registry
on:
  pull_request:
    branches:
      - master

jobs:
  publish-swagger-v2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Log in to ACR Azure Container Registry - ${{ env.AZURE_CONTAINER_REGISTRY_URL }}'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
