name: Publish OpenAPI specs
on:
# Temporarily changing this from push to pull_request to test it without pushing to master
# TODO: Change to push just before merge
#  push:
  pull_request:
    branches:
      - "master"

jobs:
  publish-pre-api:
    uses: ./.github/workflows/shared-openapi-publish-steps.yaml
    secrets:
      SWAGGER_PUBLISHER_API_TOKEN: ${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}
    with:
      test_to_run: 'uk.gov.hmcts.reform.preapi.openapi.OpenAPIPublisher'
      api_name_to_build: 'pre-api'
      api_name_to_publish: 'pre-api'
      java_version: 17
  publish-b2c-api:
    uses: ./.github/workflows/shared-openapi-publish-steps.yaml
    secrets:
      SWAGGER_PUBLISHER_API_TOKEN: ${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}
    with:
      test_to_run: 'uk.gov.hmcts.reform.preapi.openapi.OpenAPIPublisher'
      java_version: 17
      api_name_to_build: 'b2c-api'
      api_name_to_publish: 'pre-api-b2c'
