name: Publish OpenAPI specs to CNP API repository
on:
  push:
    branches:
      - "master"

jobs:
  publish-pre-api:
    uses: ./.github/workflows/commit-docs-to-cnp-api-repo.yaml
    secrets:
      SWAGGER_PUBLISHER_API_TOKEN: ${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}
    with:
      API_NAME_INTERNAL: 'pre-api'
      API_NAME_EXTERNAL: 'pre-api'
  publish-b2c-api:
    uses: ./.github/workflows/commit-docs-to-cnp-api-repo.yaml
    secrets:
      SWAGGER_PUBLISHER_API_TOKEN: ${{ secrets.SWAGGER_PUBLISHER_API_TOKEN }}
    with:
      API_NAME_INTERNAL: 'b2c-api'
      API_NAME_EXTERNAL: 'pre-api-b2c'
