name: Publish Swagger V2
on:
  pull_request:
    branches:
      - master

jobs:
  publish-swagger-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install -g api-spec-converter

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run OpenAPI Publisher
        run: ./gradlew integration --tests 'uk.gov.hmcts.reform.preapi.openapi.OpenAPIPublisherTest'

      - name: Convert OpenAPI to Swagger v2
        run: |
          api-spec-converter \
            --to=swagger_2 \
            --from=openapi_3 \
            --syntax=yaml \
            --order=alpha /tmp/openapi-specs.json > pre-api.yaml
          sed 's/basePath\: \//basePath\: \/pre-api/g' pre-api.yaml > pre-api2.yaml && \
          sed 's/\- http/\- https/g' pre-api2.yaml > pre-api.yaml && \
          rm -f pre-api2.yaml

      - name: Save swagger for staging
        run: |
          sed -E "s/(host\: .+)/host\: 'sds-api-mgmt.staging.platform.hmcts.net'/g" pre-api.yaml > pre-api-stg.yaml

      - name: Increment APIm revision
        run: |
          current_revision=$(grep -i 'revision' infrastructure/main.tf | grep -oE '[0-9]+')
          new_revision=$((current_revision + 1))
          awk -v new_revision="$new_revision" 'BEGIN{FS=OFS="\""} /revision/{$2=new_revision}1' infrastructure/main.tf > temp && mv temp infrastructure/main.tf

      - name: Bump APIm revision and commit Swagger v2 spec to branch
        run: |
          git config --global user.name 'PRE DevOps'
          git config --global user.email '138598290+pre-devops@users.noreply.github.com'
          git add pre-api-stg.yaml
          git add infrastructure/main.tf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Swagger v2 Spec"; git push)
