name: Publish OpenAPI specs
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  publish-swagger-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-npm@v1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: npm install -g api-spec-converter

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run OpenAPI Publisher
        run: ./gradlew integration --tests 'uk.gov.hmcts.reform.preapi.openapi.OpenAPIPublisherTest'

      - name: Convert OpenAPI to Swagger v2
        run: |
          api-spec-converter \
            --to=swagger_2 \
            --from=openapi_3 \
            --syntax=yaml \
            --order=alpha /tmp/openapi-specs.json > pre-api.yaml
          sed 's/basePath\: \//basePath\: \/pre-api/g' pre-api.yaml > pre-api2.yaml && \
          sed 's/\- http/\- https/g' pre-api2.yaml > pre-api.yaml && \
          rm -f pre-api2.yaml

      - name: Save swagger for staging
        run: |
          sed -E "s/(host\: .+)/host\: 'sds-api-mgmt.staging.platform.hmcts.net'/g" pre-api.yaml > pre-api-stg.yaml

      - name: Commit Swagger v2 spec to branch
        run: |
          git config --global user.name 'Swagger V2 bot'
          git config --global user.email 'jasonpaige@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git pull
          git add pre-api-stg.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Swagger v2 Spec"; git push --set-upstream upstream master)
