name: Generate OpenAPI specs
on:
  workflow_call:
    inputs:
      API_NAME:
        required: true
        type: string
        description: The name of the API, used for naming the output file. Must be unique across all APIs.
          Needs to match an API defined in application.yaml > springdoc.swagger-ui.urls

jobs:
  generate-openapi-specs:
    env:
      API_NAME: ${{ inputs.API_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run OpenAPI Publisher
        env:
          RUN_DB_MIGRATION_ON_STARTUP: false
        run: |
          ./gradlew buildOpenApiSpecs --tests 'uk.gov.hmcts.reform.preapi.openapi.OpenAPIPublisher'
          echo "Generated OpenAPI doc for ${API_NAME}"
          ls "specs/${API_NAME}.json"

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Increment APIm revision
        run:  bash scripts/increment-apim-revision-and-commit.sh
