name: Generate OpenAPI specs
on:
  workflow_call:
    inputs:
      API_NAME:
        required: true
        type: string
        description: The name of the API, used for naming the output file. Must be unique across all APIs.
          Needs to match an API defined in application.yaml > springdoc.swagger-ui.urls

jobs:
  generate-openapi-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run OpenAPI Publisher
        env:
          RUN_DB_MIGRATION_ON_STARTUP: false
          API_NAME: ${{ inputs.API_NAME }}
        run: ./gradlew buildOpenApiSpecs --tests 'uk.gov.hmcts.reform.preapi.openapi.OpenAPIPublisher'

  convert-openapi-to-swagger:
    needs: generate-openapi-specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install -g api-spec-converter --ignore-scripts

      - name: Convert OpenAPI to Swagger v2
        env:
          RUN_DB_MIGRATION_ON_STARTUP: false
          API_NAME: ${{ inputs.API_NAME }}
        run: |
          api-spec-converter \
            --to=swagger_2 \
            --from=openapi_3 \
            --syntax=yaml \
            --order=alpha "specs/${API_NAME}.json" > "${API_NAME}.yaml"
          sed 's/basePath\: \//basePath\: \/${API_NAME}/g' "${API_NAME}.yaml" > "${API_NAME}2.yaml" && \
          sed 's/\- http/\- https/g' "${API_NAME}2.yaml" > "${API_NAME}.yaml" && \
          rm -f "${API_NAME}2.yaml"

      - name: Save swagger for staging
        run: |
          sed -E "s/(host\: .+)/host\: 'sds-api-mgmt.staging.platform.hmcts.net'/g" "${API_NAME}.yaml" > "${API_NAME}-stg.yaml"

  increment-api-version:
    needs: convert-openapi-to-swagger
    env:
      API_NAME: ${{ inputs.API_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: wget master main.tf
        uses: wei/wget@c15e476d1463f4936cb54f882170d9d631f1aba5
        with:
          args: -O main.tf https://raw.githubusercontent.com/hmcts/pre-api/master/infrastructure/main.tf

      - name: wget master pre-api-stg.yaml
        uses: wei/wget@c15e476d1463f4936cb54f882170d9d631f1aba5
        with:
          args: -O master.pre-api-stg.yaml https://raw.githubusercontent.com/hmcts/pre-api/master/pre-api-stg.yaml

      - name: Increment APIm revision
        run: |
          git config --global user.name 'PRE DevOps'
          git config --global user.email '138598290+pre-devops@users.noreply.github.com'

          CHANGED=$(git diff --name-only pre-api-stg.yaml specs/${API_NAME}.json)
          commit_message=""
          if [ "$CHANGED" != "" ]; then
            echo "OpenAPI spec has been updated this commit"
            git add -u pre-api-stg.yaml "specs/${API_NAME}.json"
            commit_message="Update Swagger v2 Spec"
          fi

          # get the revision number from the main.tf file in master
          master_revision=$(grep -i 'api_revision' main.tf | grep -oE '[0-9]+')
          branch_revision=$(grep -i 'api_revision' infrastructure/main.tf | grep -oE '[0-9]+')

          if cmp "master.pre-api-stg.yaml" "pre-api-stg.yaml"; then
            echo "No changes to pre-api-stg.yaml"
            if [[ $master_revision -gt $branch_revision ]]; then
              echo "Master revision is greater than branch revision"
              awk -v new_revision="$master_revision" 'BEGIN{FS=OFS="\""} /api_revision=/{$2=new_revision}1' infrastructure/main.tf > temp && mv temp infrastructure/main.tf
              git add infrastructure/main.tf

              commit_message="${commit_message} Bump APIm revision to $master_revision"
            fi
          else
            echo "API Spec has changed compared to master, ensure revision is incremented"
            if [[ $master_revision -ge $branch_revision ]]; then
              echo "Master revision $master_revision is less than/equal to branch revision $branch_revision"
              new_revision=$((master_revision + 1))
              echo "New revision number: $new_revision"
              sed -e "s/^  api_revision.*\"$branch_revision\"/  api_revision = \"$new_revision\"/"  infrastructure/main.tf > temp && mv temp infrastructure/main.tf
              git add infrastructure/main.tf
              commit_message="${commit_message} Bumped APIm revision to $new_revision"
            fi
          fi

          # cleanup
          rm -f main.tf master.pre-api-stg.yaml

          # commit and push if there are changes
          if [ -n "$commit_message" ]; then
            git config --global user.name 'PRE DevOps'
            git config --global user.email '138598290+pre-devops@users.noreply.github.com'
            git commit -m "$commit_message"
            git push
          fi
          echo "done"
